### PR TITLE
added Docker capability

### PR DESCRIPTION
**Pull request by rendall**
Make it easier to setup and run the app as a website. Install Docker on your system, build the image as represented by the Dockerfile, then run it.

I added this information to the README.md:

 * Download and install [Docker](https://docs.docker.com/install/) and make sure it's is in your PATH environment variable
 * Using a terminal (Linux or iOS) or PowerShell (Windows 10) navigate to the project's directory
 * Type `docker build -t kai:1.0 .`
 * Type `docker run -p 8080:8080 kai:1.0`
 * Open http://localhost:8080

### CODE REVIEW

**Comment by rendall** [comment]
Let me know if there are any questions or improvements I can make.  Happy to help.

**Comment by tonib** [comment]
Ok, accepted, but, is it right an image of 1 GB?
```
sudo docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kai                 1.0                 1c7e6a7cf537        11 hours ago        1.02GB
```
I'll add you to the authors list as "Rendall". If you want other name or you don't want to be added, please, let me know

**Comment by rendall** [comment]
Thanks for the add, Toni.

That is a good point about the size. I will see how I can reduce that, perhaps by using a smaller base node image.

**Comment by rendall** [comment]
Also, I wonder if the instructions should make it clear that the build command only needs to happen once. I'll fix these and a try a new PR.

**Pull request merged**
