### PR TITLE
(Work in progress) Book 11

### PR DESCRIPTION
**Pull request by jakl**
I'm working on book 11, currently done through sect13. I'll try to be responsive to comments. This is my first time looking at this repo and working (indirectly) with typescript, although I'm very familiar with JS. I welcome any and all feedback and suggestions.

### CODE REVIEW

**Comment by tonib** [comment]
Hello and thank you. I did some changes:
- Added you ("James Koval") as author on "About the book"
- Added pickMaximum="6" to the equipment section
- The "index" property for objects should be numeric. You can test the mechanics syntax with the "Tests" link > "Test mechanics" button
- Sect 1: Changed the "zero" case by a zeroAsTen="true", and disabled the choices if you have not picked the random table
- Moved sect20 to the bottom

Comments:
- Sect equipment: I suspect the two free meals should be picked only if it's your first player book, I'm not sure. You  can do is surrounding the with a ' test expression="[KAILEVEL] == 3" ' (the level at the first player book)
- sect2: Probable loss of a fireseed (not sure, see "Origin sections")
- sect8: Probable pick of a sword (not sure, see "Origin sections")
- sect7: You can add new objects at objects.xml (documentation at README-objects.md). Check the "captaindvalsword" object, I think it's similar
- sect20: It's OK, but it can be written with less code. There are cases where it's easier start with a "default" state, and then change it if it's needed. Ex. it can be written like this:
```xml
         <choiceState section="sect145" set="disabled" />
          <test hasDiscipline="dvnation">
              <test expression="[KAILEVEL] >= 5">
                <choiceState section="sect145" set="enabled" />
                <choiceState section="sect297" set="disabled" />
              </test>
          </test>
```

**Comment by jakl** [comment]
Oh cool, thanks, I'll have a look.

**Comment by tonib** [comment]
Hi, 
I think I will release a new version with books 9 / 10 this week. I don't know if you are still working on book 11. I mean, it's OK if not, but I need to know it, because if not, I will continue with book 11.
If you continue with book book 11, I will start working on book 12.
Cheers!

**Comment by jakl** [comment]
Hi Toni, I did some more work on this yesterday, however I'm making slow progress. I just did through sect22. I think I'd like to work more on this because I love the books and this is a good project. When do you think book 11 should be completed by? Maybe I could work faster.

**Comment by tonib** [comment]
Hello, I'm finishing the book 12, probably next week. As there are no plans to add more books, I'll continue with the book 11. Did you make any progress? Could you send a pull request with it?
Thank you

**Comment by jakl** [comment]
Sorry I didn't make significant progress.

**Comment by tonib** [comment]
No problem!

**Pull request merged**
